import type { BlogPost } from "@/lib/blog-types";

export const post: BlogPost = {
  slug: "electricien-urgence-montreal-24h-quand-appeler",
  title: "Électricien d'urgence 24h à Montréal : quand appeler et le déroulement",
  category: "Urgence électrique",
  excerpt:
    "Quand appeler un électricien d'urgence à Montréal et comment se passe l'intervention : arrivée en moins d'une heure, diagnostic gratuit, prix annoncé d'avance.",
  date: "2026-09-10",
  keywords: [
    "électricien d'urgence Montréal",
    "électricien 24h Montréal",
    "urgence électrique Montréal",
    "dépannage électrique urgent",
    "électricien de garde Montréal",
    "quand appeler un électricien d'urgence",
    "électricien d'urgence Laval",
    "électricien d'urgence Longueuil Rive-Sud",
    "intervention électrique en moins d'une heure",
    "électricien licencié CMEQ RBQ",
  ],
  relatedServiceSlug: "depannage-urgence",
  content: [
    "Il est 2 h du matin. Le disjoncteur principal vient de sauter pour la troisième fois, une odeur de plastique chaud monte du sous-sol et la moitié de la maison est dans le noir. Vous tapez « électricien d'urgence Montréal » sur votre téléphone, mais vous hésitez : est-ce que ça justifie vraiment un appel en pleine nuit ? Et si oui, qu'est-ce qui va se passer une fois le numéro composé ?",
    "Ces deux questions méritent des réponses claires, parce qu'elles décident de la suite : une nuit tranquille ou une nuit à risque. Ce guide vous explique ce qui constitue une véritable urgence électrique, ce qui peut attendre le matin, comment se déroule une intervention 24h de A à Z, ce que l'électricien apporte dans son camion, pourquoi la licence n'est pas un détail, et quels secteurs nous couvrons dans le Grand Montréal.",
    "## Urgence électrique ou simple inconvénient : comment trancher",
    "La règle tient en une phrase : si le problème présente un risque d'incendie, d'électrocution ou de dommage qui s'aggrave avec le temps, c'est une urgence. Si le problème est stable, isolé, sans chaleur, sans odeur et sans bruit, il peut généralement attendre les heures ouvrables. Voici comment appliquer cette règle concrètement.",
    "### Les situations qui justifient un appel immédiat, jour ou nuit",
    "- Une odeur de brûlé, de plastique chaud ou de caoutchouc près d'une prise, d'un interrupteur ou du panneau électrique.",
    "- Des étincelles, un grésillement ou un bourdonnement provenant d'un mur ou du panneau.",
    "- Un disjoncteur qui saute à répétition, même après avoir débranché les appareils du circuit.",
    "- Une panne partielle : une partie de la maison sans courant, ou des lumières qui varient d'intensité alors que les voisins ont de l'électricité.",
    "- Une décharge ou un picotement en touchant un robinet, un appareil ou une poignée métallique.",
    "- Une panne complète l'hiver, quand la maison refroidit et que le chauffage dépend de l'électricité.",
    "- De l'eau qui a atteint le panneau, des prises ou des appareils branchés.",
    "- Un commerce, un restaurant ou un immeuble locatif privé de courant, avec des frigos, un système d'alarme ou des locataires en jeu.",
    "### Ce qui peut raisonnablement attendre le lendemain",
    "- Une seule prise qui ne fonctionne plus, sans chaleur, sans odeur et sans trace noire.",
    "- Un interrupteur qui « clique » mal mais qui allume encore la lumière normalement.",
    "- Un luminaire qui a grillé, alors que les autres appareils du même circuit fonctionnent.",
    "- Une prise extérieure hors service en été, quand rien de critique n'y est branché.",
    "- Un projet d'ajout de prise, de gradateur ou de circuit pour la cuisine ou le garage.",
    "Dans le doute, appelez quand même. Un électricien d'urgence sérieux ne vous enverra pas un camion pour rien : il vous posera trois ou quatre questions au téléphone et vous dira honnêtement si ça peut attendre. C'est exactement ce que fait notre équipe de [dépannage électrique d'urgence](/services/depannage-urgence) à chaque appel.",
    "## Comment se déroule une intervention d'urgence 24h, étape par étape",
    "Beaucoup de gens hésitent à appeler la nuit parce qu'ils ne savent pas à quoi s'attendre. Voici le déroulement réel d'une intervention, du premier coup de fil à la remise sous tension.",
    "### 1. L'appel : quelques questions, puis un électricien en route",
    "Quand vous composez le (438) 338-4113, une personne vous répond, pas une boîte vocale. Elle vous demande ce que vous observez (odeur, bruit, disjoncteur, zone touchée), depuis quand, et si quelqu'un est en danger. Elle vous donne les consignes de sécurité immédiates et confirme le délai. L'appel prend deux ou trois minutes, et l'électricien de garde le plus proche part vers chez vous.",
    "### 2. L'arrivée en moins d'une heure",
    "Nos électriciens sont basés dans le Grand Montréal et se répartissent les secteurs pour arriver en moins d'une heure, 24/7, 365 jours par année. Pendant ce temps, vous gardez la ligne ouverte : si la situation change, vous nous rappelez et nous ajustons les consignes. Notre article sur [quoi faire pendant une panne électrique la nuit](/blog/panne-electrique-nuit-quoi-faire-en-attendant-electricien) détaille les gestes utiles en attendant.",
    "### 3. Le diagnostic sur place, gratuit",
    "L'électricien commence par sécuriser : il coupe ou isole ce qui doit l'être et vérifie qu'il n'y a ni chaleur anormale ni risque immédiat. Ensuite, il cherche la cause réelle plutôt que le symptôme. Il mesure la tension aux bornes du panneau, teste les circuits, inspecte les connexions suspectes et, au besoin, utilise une caméra thermique pour repérer un point chaud invisible à l'œil nu. Ce diagnostic est gratuit, même en pleine nuit.",
    "### 4. Le prix, annoncé avant de toucher à quoi que ce soit",
    "Une fois la cause identifiée, l'électricien vous explique ce qu'il a trouvé, ce qui doit être réparé maintenant et ce qui peut attendre. Il vous donne un prix clair pour la réparation. Rien ne commence sans votre accord. Et parce que nous n'appliquons aucune surcharge de nuit, de fin de semaine ou de jour férié, le montant est le même qu'un mardi après-midi. Pour comprendre ce qui compose une facture d'urgence, lisez notre guide sur [le coût d'un électricien d'urgence à Montréal](/blog/cout-electricien-urgence-montreal-nuit-fin-de-semaine).",
    "### 5. La réparation, la remise sous tension et la vérification",
    "La plupart des urgences se règlent sur place : [remplacement d'un disjoncteur](/services/remplacement-disjoncteur) défectueux, reprise d'une connexion desserrée, remplacement d'une prise brûlée, réparation d'un fil neutre endommagé. L'électricien remet ensuite le courant, vérifie chaque circuit touché, mesure à nouveau la tension et s'assure que tout est stable avant de partir. Vous recevez une facture détaillée qui décrit l'intervention.",
    "## Ce qu'il y a dans le camion d'un électricien d'urgence",
    "Un vrai service 24h ne fonctionne pas avec une boîte à outils et de la bonne volonté. Le camion est préparé pour régler le problème du premier coup, sans revenir le lendemain avec la pièce manquante. Voici ce qu'on y trouve.",
    "- Des disjoncteurs des principales marques présentes à Montréal, en différents calibres, y compris des modèles pour panneaux plus anciens.",
    "- Des prises, interrupteurs, prises DDFT (salle de bain, cuisine, extérieur) et plaques de remplacement.",
    "- Du fil, des connecteurs, des boîtes de jonction et des serre-fils pour reprendre une connexion défaillante.",
    "- Un multimètre, une pince ampèremétrique, un détecteur de tension sans contact et un testeur de prises.",
    "- Une caméra thermique pour localiser une surchauffe derrière un mur ou dans un panneau.",
    "- L'équipement de protection : gants isolants, lunettes, lampes frontales et éclairage portatif pour travailler dans le noir.",
    "- Un détecteur d'humidité et de quoi sécuriser un panneau touché par l'eau.",
    "Cette préparation est ce qui permet de régler la majorité des urgences en une seule visite, ce qui compte doublement quand vous êtes sans chauffage ou sans frigo.",
    "## Pourquoi exiger un électricien licencié, même à 3 h du matin",
    "Au Québec, les travaux d'électricité doivent être exécutés par un entrepreneur électricien titulaire d'une licence de la CMEQ (Corporation des maîtres électriciens du Québec) et de la RBQ. Ce n'est pas une formalité. La licence garantit que l'électricien a la formation, l'assurance et le cautionnement nécessaires, et que l'intervention respecte le Code de l'électricité. Une réparation faite par quelqu'un qui n'a pas de licence peut annuler votre couverture d'assurance habitation en cas de sinistre.",
    "La nuit, la tentation est grande d'accepter le premier « bricoleur » disponible sur un site de petites annonces. Résistez. Une urgence électrique est précisément le moment où une erreur coûte le plus cher : un disjoncteur mal calibré, une connexion reprise à la va-vite ou un panneau refermé sans vérification peuvent provoquer un incendie quelques jours plus tard. Nos électriciens sont licenciés, équipés et formés pour intervenir en sécurité, de jour comme de nuit.",
    "## Les secteurs couverts dans le Grand Montréal",
    "Notre service d'urgence couvre l'île de Montréal et les couronnes. Les électriciens de garde sont répartis pour tenir la promesse du délai d'une heure.",
    "- Montréal : tous les arrondissements, du Plateau à Pointe-aux-Trembles, de Ville-Marie à Saint-Laurent, incluant Rosemont, Villeray, Ahuntsic, LaSalle, Verdun et Anjou.",
    "- Laval : Chomedey, Vimont, Sainte-Rose, Duvernay, Fabreville et le reste de l'île Jésus.",
    "- Rive-Sud : Longueuil, Brossard, Saint-Lambert, Boucherville, Saint-Hubert et les environs.",
    "- Rive-Nord : Terrebonne, Mascouche, Repentigny, Blainville et les villes voisines.",
    "## En attendant l'électricien : les gestes qui protègent",
    "Quelques réflexes simples réduisent le risque pendant le délai d'arrivée.",
    "- Si vous voyez des flammes ou de la fumée, sortez et composez le 911 avant toute autre chose.",
    "- Coupez le disjoncteur concerné, ou le disjoncteur principal si vous ne savez pas lequel, à condition de pouvoir le faire les mains sèches et sans toucher un élément chaud ou mouillé.",
    "- N'ouvrez jamais le panneau électrique vous-même : le boîtier reste sous tension même quand les disjoncteurs sont coupés.",
    "- Débranchez les appareils sensibles (ordinateur, télévision, électroménagers) pour éviter les dommages à la remise sous tension.",
    "- Éloignez les enfants, les animaux et les matières inflammables de la zone touchée.",
    "- Gardez une lampe de poche à portée de main plutôt qu'une chandelle.",
    "## Conclusion : quand ça sent, ça grésille ou ça saute, appelez",
    "Une urgence électrique se reconnaît à trois signaux : la chaleur, le bruit et la répétition. Une odeur de brûlé, un grésillement, un disjoncteur qui saute encore et encore, une panne partielle ou un choc au toucher ne sont pas des inconvénients : ce sont des problèmes en cours à l'intérieur de vos murs. Face à ces signes, un électricien d'urgence à Montréal arrive en moins d'une heure, pose un diagnostic gratuit, vous annonce le prix avant de commencer et répare sans surcharge, peu importe l'heure.",
    "Vous vivez cette situation en ce moment ? Appelez-nous au [(438) 338-4113](tel:+14383384113). Pour un problème qui peut attendre, vous pouvez aussi [demander une intervention en ligne](/contact) et nous planifierons une visite à votre convenance.",
  ],
  faq: [
    {
      question: "Comment savoir si mon problème électrique est une vraie urgence ?",
      answer:
        "Posez-vous une question : y a-t-il un risque d'incendie, d'électrocution ou un dommage qui s'aggrave ? Odeur de brûlé, étincelles, grésillement, disjoncteur qui saute à répétition, panne partielle, choc au toucher, eau au panneau : ce sont des urgences. Une seule prise morte, froide et sans odeur peut attendre. Dans le doute, appelez : nous vous dirons honnêtement au téléphone si ça justifie un déplacement.",
    },
    {
      question: "En combien de temps un électricien d'urgence arrive-t-il à Montréal ?",
      answer:
        "Nos électriciens de garde sont répartis dans le Grand Montréal pour arriver en moins d'une heure, 24/7, 365 jours par année, à Montréal, Laval, Longueuil, Brossard, Terrebonne et sur les deux rives. Dès l'appel, vous recevez les consignes de sécurité à suivre en attendant : couper le disjoncteur concerné si c'est possible en toute sécurité, ne pas ouvrir le panneau et composer le 911 en cas de fumée ou de flammes.",
    },
    {
      question: "Le diagnostic est-il vraiment gratuit, même la nuit ?",
      answer:
        "Oui. L'électricien sécurise l'installation, identifie la cause réelle du problème et vous l'explique sans frais, à toute heure. Vous recevez ensuite un prix clair pour la réparation, et rien ne commence sans votre accord. Si vous décidez de ne pas procéder, ou si le problème relève d'Hydro-Québec, vous ne payez pas de diagnostic. Il n'y a aucune surcharge de nuit, de fin de semaine ou de jour férié.",
    },
    {
      question: "Pourquoi est-ce important que l'électricien d'urgence soit licencié ?",
      answer:
        "Au Québec, les travaux électriques doivent être faits par un entrepreneur licencié CMEQ / RBQ. La licence garantit la formation, l'assurance et le respect du Code de l'électricité. Une réparation faite par une personne sans licence peut être dangereuse, non conforme, et compromettre votre couverture d'assurance habitation en cas de sinistre. En urgence, c'est encore plus vrai : une erreur commise dans la précipitation peut provoquer un incendie quelques jours plus tard.",
    },
    {
      question: "Que dois-je faire en attendant l'arrivée de l'électricien ?",
      answer:
        "Si vous voyez des flammes ou de la fumée, sortez et composez le 911. Sinon, coupez le disjoncteur concerné ou le principal si vous pouvez le faire les mains sèches, sans toucher un élément chaud ou mouillé. Débranchez les appareils sensibles, éloignez les enfants, les animaux et les matières inflammables, utilisez une lampe de poche plutôt qu'une chandelle, et n'ouvrez jamais le panneau électrique. Dégagez l'accès au panneau pour gagner du temps.",
    },
  ],
};
