import type { BlogPost } from "@/lib/blog-types";

export const post: BlogPost = {
  slug: "hydro-quebec-ou-electricien-qui-appeler-panne",
  title: "Panne de courant : Hydro-Québec ou électricien d'urgence ? Qui appeler",
  category: "Panne électrique",
  excerpt:
    "Panne de courant à Montréal : Hydro-Québec ou électricien ? Ce qui relève du réseau, ce qui est à votre charge, les signes que c'est chez vous et qui appeler.",
  date: "2026-08-27",
  keywords: [
    "Hydro-Québec ou électricien panne",
    "panne de courant qui appeler",
    "panne électrique Montréal",
    "Info-pannes Hydro-Québec",
    "entrée électrique responsabilité propriétaire",
    "mât de branchement réparation",
    "panne partielle maison",
    "électricien d'urgence Montréal",
    "réenclenchement Hydro-Québec électricien",
    "diagnostic électrique urgence",
  ],
  relatedServiceSlug: "diagnostique-electrique",
  content: [
    "Le courant vient de couper. Premier réflexe : regarder dehors. Si toute la rue est dans le noir, on hausse les épaules, on signale la panne à Hydro-Québec et on attend. Mais si la maison du voisin est éclairée, ou si chez vous seule la moitié des pièces fonctionne, la question devient plus compliquée : est-ce Hydro-Québec qui doit venir, ou un électricien ? Appeler le mauvais numéro, c'est perdre une heure, parfois une nuit entière.",
    "La confusion est normale. La frontière entre le réseau public et votre installation privée passe littéralement sur votre mur extérieur, et peu de gens savent exactement où. Cet article vous explique qui est responsable de quoi, comment reconnaître en deux minutes une panne qui vient de chez vous, quels risques vous courez à attendre, et dans quels cas l'électricien et Hydro-Québec doivent travailler ensemble.",
    "## Qui est responsable de quoi : la frontière sur votre mur",
    "Hydro-Québec est responsable du réseau de distribution jusqu'au point de raccordement de votre maison. Vous êtes responsable de tout ce qui vient après. Voici la répartition précise.",
    "### Ce qui appartient à Hydro-Québec",
    "- Les lignes de distribution dans la rue, les poteaux et les transformateurs.",
    "- Le branchement aérien (les fils qui vont du poteau jusqu'à votre mât) ou souterrain jusqu'à votre maison.",
    "- Le compteur lui-même, qu'Hydro-Québec installe, scelle et remplace.",
    "- Les raccordements aux extrémités du branchement, sur le poteau et au point de jonction avec votre entrée.",
    "### Ce qui vous appartient, en tant que propriétaire",
    "- Le mât de branchement (la tige métallique sur le toit ou le mur) et sa tête d'ancrage.",
    "- L'entrée électrique : le conduit, les câbles qui descendent du mât jusqu'à l'embase du compteur, et l'embase elle-même.",
    "- Le disjoncteur principal et le panneau électrique.",
    "- Tout le câblage intérieur, les prises, les interrupteurs, les luminaires et les appareils.",
    "- La mise à la terre de l'installation.",
    "Retenez la logique : jusqu'au compteur, c'est Hydro-Québec ; à partir de l'embase du compteur vers l'intérieur, et le mât qui la soutient, c'est vous. Quand le problème est de votre côté, Hydro-Québec ne peut pas le réparer, même si un monteur se déplace : il constatera, coupera l'alimentation par sécurité si nécessaire, et vous dira d'appeler un électricien licencié.",
    "## Info-pannes : le premier réflexe, avant tout appel",
    "Avant de composer quelque numéro que ce soit, ouvrez Info-pannes d'Hydro-Québec sur votre téléphone ou leur application mobile. La carte affiche en temps réel les pannes signalées, le nombre de clients touchés et l'heure de rétablissement estimée. Si votre secteur y figure, inutile d'appeler un électricien : la panne vient du réseau et Hydro-Québec est déjà au courant.",
    "Si votre adresse n'apparaît pas et que les voisins ont du courant, signalez tout de même la panne à Hydro-Québec (votre appel est enregistré), puis passez à la vérification suivante : les signes que le problème est chez vous.",
    "## Les signes que la panne vient de chez vous",
    "Certains symptômes sont presque impossibles à attribuer au réseau. Quand vous en observez un, l'électricien est le bon appel.",
    "- Une panne partielle : certaines pièces ou certains appareils fonctionnent, d'autres non, sans qu'un disjoncteur ait déclenché. Cela pointe souvent vers une phase perdue à l'entrée électrique ou une connexion défaillante au panneau.",
    "- Des lumières qui varient : très vives dans une pièce, faibles dans une autre, ou qui pulsent quand un gros appareil démarre. C'est le signe classique d'un neutre défectueux, dangereux pour vos appareils.",
    "- Les voisins ont du courant et Info-pannes ne signale rien dans votre secteur.",
    "- Le disjoncteur principal a sauté et ressaute quand vous le réenclenchez.",
    "- Une odeur de brûlé, un grésillement ou une chaleur anormale au panneau, à une prise ou à l'entrée électrique.",
    "- Un mât de branchement incliné, arraché ou dont les fils sont tendus après une tempête, une chute de branche ou de la glace.",
    "- De l'eau ou de la rouille au panneau, ou une panne survenue après une inondation au sous-sol.",
    "Pour la panne partielle en particulier, notre article sur [la moitié de la maison sans courant](/blog/moitie-maison-sans-courant-panne-partielle) explique en détail pourquoi ce symptôme ne doit jamais être ignoré.",
    "## Les risques d'attendre ou d'appeler le mauvais numéro",
    "Une panne qui vient de chez vous n'est pas un simple inconvénient qu'on règle lundi. Selon la cause, les risques sont réels.",
    "- Neutre défectueux : la tension se déséquilibre entre les circuits. Certains appareils reçoivent beaucoup trop de tension et peuvent griller ou prendre feu ; d'autres tournent en sous-tension et s'abîment.",
    "- Connexion desserrée à l'entrée ou au panneau : elle chauffe, fait fondre son isolant et peut déclencher un incendie dans le mur ou le panneau, souvent la nuit, quand personne ne surveille.",
    "- Mât endommagé : les câbles de branchement peuvent se rompre ou toucher le toit. Ne touchez jamais à un fil tombé ou à un mât affaissé, et tenez tout le monde à distance.",
    "- Panne l'hiver : sans électricité, une maison montréalaise perd sa chaleur en quelques heures. Les tuyaux gèlent, les dégâts d'eau suivent.",
    "- Réenclenchements répétés du disjoncteur principal : chaque tentative aggrave la surchauffe de la connexion en cause.",
    "Dans tous ces cas, la règle de sécurité ne change pas : n'ouvrez jamais le panneau vous-même, coupez le disjoncteur principal si vous pouvez le faire en toute sécurité, et composez le 911 en présence de flammes ou de fumée.",
    "## Quand l'électricien et Hydro-Québec doivent travailler ensemble",
    "Certaines réparations exigent les deux parties. C'est là qu'un électricien d'urgence qui connaît les procédures d'Hydro-Québec vous fait gagner beaucoup de temps.",
    "### Le réenclenchement après une coupure",
    "Quand l'entrée électrique, le mât ou l'embase doivent être réparés, Hydro-Québec doit d'abord couper l'alimentation au poteau, car ces éléments restent sous tension même quand le disjoncteur principal est ouvert. L'électricien fait la demande de coupure, effectue la réparation, puis demande le rebranchement. Un électricien licencié sait comment formuler ces demandes pour que le monteur passe rapidement, y compris en dehors des heures de bureau lorsqu'il s'agit d'une urgence.",
    "### Le remplacement de l'entrée électrique ou du panneau",
    "Une entrée électrique corrodée, un mât arraché ou un [panneau électrique](/services/panneau-electrique) qui a subi un dégât d'eau ou une surchauffe demandent une coordination : coupure par Hydro-Québec, travaux par l'électricien, vérification, puis rebranchement. Notre équipe prend en charge l'ensemble du processus pour que vous n'ayez pas à jongler entre deux interlocuteurs.",
    "### Le compteur qui semble défectueux",
    "Si l'électricien constate que le problème vient du compteur lui-même ou du branchement d'Hydro-Québec, il vous le dira clairement : c'est à Hydro-Québec de le remplacer, et il vous aidera à faire la demande. Vous ne payez pas une réparation qui ne vous appartient pas.",
    "## Combien ça coûte, et qui paie",
    "Une panne de réseau ne vous coûte rien : Hydro-Québec répare son réseau à ses frais. Une panne chez vous est à la charge du propriétaire (ou du propriétaire de l'immeuble si vous êtes locataire). Le montant dépend de la cause : resserrer une connexion et remplacer un disjoncteur n'ont rien à voir avec le remplacement complet d'une entrée électrique ou d'un panneau.",
    "Ce qui ne devrait pas varier, c'est la façon de procéder. Chez Urgence Électricien MTL, le [diagnostic électrique](/services/diagnostique-electrique) sur place est gratuit, le prix vous est annoncé avant de commencer, et il n'y a aucune surcharge de nuit, de fin de semaine ou de jour férié. Si la panne vient finalement d'Hydro-Québec, vous le saurez en toute franchise, sans facture pour une réparation qui n'a pas eu lieu. Pour des ordres de grandeur par type d'intervention, consultez notre guide sur [le coût d'un électricien d'urgence à Montréal](/blog/cout-electricien-urgence-montreal-nuit-fin-de-semaine).",
    "## En résumé : qui appeler, dans quel ordre",
    "- Toute la rue est dans le noir et Info-pannes signale votre secteur : Hydro-Québec, puis patience.",
    "- Les voisins ont du courant, votre maison est entièrement ou partiellement sans électricité : électricien d'urgence.",
    "- Lumières qui varient, panne partielle, disjoncteur principal qui ressaute, odeur de brûlé : électricien d'urgence, sans attendre.",
    "- Mât arraché, fil tombé, fumée ou flammes : 911 d'abord, puis l'électricien, qui coordonnera avec Hydro-Québec.",
    "- Vous hésitez : appelez-nous. Nous vous dirons honnêtement, au téléphone, si le problème relève du réseau ou de votre installation.",
    "## Conclusion : le réseau à Hydro-Québec, l'installation à l'électricien",
    "Hydro-Québec s'occupe du réseau jusqu'au compteur ; l'électricien s'occupe du mât, de l'entrée électrique, du panneau et de tout ce qui suit. Quand les voisins ont du courant et que vous n'en avez pas, ou que la maison fonctionne à moitié, le problème est presque toujours de votre côté, et il ne s'améliore pas en attendant. Un électricien d'urgence licencié pose le diagnostic gratuitement, vous annonce le prix et coordonne avec Hydro-Québec si la réparation l'exige.",
    "Vous êtes sans courant maintenant alors que les voisins ne le sont pas ? Appelez le [(438) 338-4113](tel:+14383384113) : réponse en moins d'une heure, 24/7, partout dans le Grand Montréal. Pour une situation qui peut attendre, [demandez une intervention en ligne](/contact).",
  ],
  faq: [
    {
      question: "Comment savoir rapidement si la panne vient d'Hydro-Québec ou de chez moi ?",
      answer:
        "Deux vérifications suffisent. Regardez si les voisins et les lampadaires ont du courant, puis consultez Info-pannes d'Hydro-Québec sur votre téléphone. Si votre secteur y figure, c'est le réseau. Si les voisins sont éclairés et que rien n'est signalé, le problème est chez vous. Une panne partielle, des lumières qui varient ou un disjoncteur principal qui ressaute confirment que l'installation privée est en cause et qu'il faut un électricien d'urgence.",
    },
    {
      question: "Hydro-Québec répare-t-elle mon mât ou mon entrée électrique ?",
      answer:
        "Non. Le mât de branchement, l'entrée électrique, l'embase du compteur, le disjoncteur principal, le panneau et le câblage intérieur appartiennent au propriétaire. Hydro-Québec ne répare que son réseau, le branchement jusqu'au mât et le compteur. Si le monteur constate un problème de votre côté, il coupera l'alimentation par sécurité et vous demandera de faire appel à un électricien licencié, qui coordonnera ensuite le rebranchement.",
    },
    {
      question: "Pourquoi les lumières varient-elles d'intensité pendant une panne partielle ?",
      answer:
        "C'est le signe classique d'un neutre défectueux à l'entrée électrique ou au panneau. La tension se déséquilibre : certains circuits reçoivent trop de tension, d'autres pas assez. Les appareils peuvent griller ou surchauffer, avec un risque d'incendie. Coupez le disjoncteur principal si vous pouvez le faire en toute sécurité, débranchez les appareils sensibles, n'ouvrez pas le panneau et appelez un électricien d'urgence sans attendre.",
    },
    {
      question: "Un électricien peut-il faire réenclencher le courant par Hydro-Québec la nuit ?",
      answer:
        "Oui, dans les cas d'urgence. Quand la réparation touche l'entrée électrique, le mât ou l'embase, Hydro-Québec doit couper l'alimentation au poteau avant les travaux, puis rebrancher ensuite. Un électricien licencié sait formuler ces demandes correctement pour accélérer le passage du monteur, y compris hors des heures de bureau. Notre équipe prend en charge cette coordination pour que vous n'ayez qu'un seul interlocuteur.",
    },
    {
      question: "Combien coûte une intervention si la panne vient finalement d'Hydro-Québec ?",
      answer:
        "Chez Urgence Électricien MTL, rien : le diagnostic sur place est gratuit, à toute heure. Si l'électricien constate que le problème vient du réseau ou du compteur, il vous le dit clairement et vous aide à faire la demande auprès d'Hydro-Québec, sans facture pour une réparation qui n'a pas eu lieu. Si le problème est chez vous, le prix est annoncé avant les travaux, sans surcharge de nuit ou de fin de semaine.",
    },
  ],
};
