import type { BlogPost } from "@/lib/blog-types";

export const post: BlogPost = {
  slug: "odeur-brule-electrique-prise-panneau-reagir-vite",
  title: "Odeur de brûlé électrique : les 5 premières minutes qui comptent",
  category: "Sécurité électrique",
  excerpt:
    "Odeur de brûlé électrique près d'une prise ou du panneau ? Protocole minute par minute, causes fréquentes et quand appeler un électricien d'urgence à Montréal.",
  date: "2026-08-06",
  keywords: [
    "odeur de brûlé électrique",
    "odeur de brûlé prise électrique",
    "odeur de plastique brûlé panneau électrique",
    "odeur de brûlé sans fumée maison",
    "que faire odeur de brûlé électrique",
    "prise qui sent le brûlé",
    "électricien d'urgence Montréal",
    "dépannage électrique urgent",
    "risque incendie électrique",
    "connexion desserrée surchauffe",
  ],
  relatedServiceSlug: "depannage-urgence",
  content: [
    "Vous entrez dans le salon et quelque chose ne va pas. Une odeur de plastique chaud, sucrée et âcre à la fois, sans aucune source visible. Pas de fumée, pas de flamme, rien qui grésille. Vous reniflez près de la télévision, puis près de la prise derrière le meuble, et là, c'est plus fort. Ce moment précis est celui où tout se joue : une odeur de brûlé électrique est le tout premier avertissement d'une surchauffe, et ce qui se passe dans les cinq minutes qui suivent détermine souvent si la soirée se termine par un appel à l'électricien ou par un appel aux pompiers.",
    "Cet article vous apprend à reconnaître l'odeur, à la localiser, et vous donne un protocole clair, minute par minute. Il explique ensuite d'où vient la surchauffe, ce que fait l'électricien à son arrivée et comment éviter que ça se reproduise. Notre équipe de [dépannage d'urgence](/services/depannage-urgence) intervient 24/7 dans le Grand Montréal, en moins d'une heure.",
    "## Reconnaître une odeur de brûlé électrique",
    "Toutes les odeurs de brûlé ne se ressemblent pas, et savoir les distinguer aide à réagir correctement.",
    "- **Plastique chaud ou caoutchouc brûlé** : c'est la plus fréquente. L'isolant d'un fil ou le boîtier d'une prise commence à fondre. Elle est souvent légère au début, puis de plus en plus présente.",
    "- **Odeur de poisson ou d'urine** : surprenante, mais typique. Certains plastiques et résines utilisés dans les prises, interrupteurs et disjoncteurs dégagent une odeur de poisson quand ils surchauffent. Beaucoup de gens cherchent une cause dans la cuisine alors que le problème est dans le mur.",
    "- **Odeur d'ozone, métallique ou « d'orage »** : elle signale un arc électrique, c'est-à-dire une étincelle qui se forme dans une connexion desserrée. C'est le signe le plus sérieux, car l'arc peut enflammer le bois ou la poussière autour de la boîte.",
    "Le point commun de ces trois odeurs : elles persistent, elles reviennent quand un appareil ou un circuit est sollicité, et elles n'ont aucune source évidente. Une odeur de brûlé sans fumée n'est pas rassurante ; c'est simplement le stade qui précède la fumée.",
    "## Localiser la source",
    "Avant de couper quoi que ce soit, prenez trente secondes pour identifier d'où vient l'odeur. Cela vous permettra de couper le bon disjoncteur et de guider l'électricien. Les cinq sources habituelles :",
    "- **Une prise de courant** : approchez la main sans toucher. Une plaque tiède ou chaude, une décoloration jaune ou brune, une fiche qui tient mal : la prise chauffe. C'est très fréquent derrière un chauffage d'appoint ou un climatiseur portatif.",
    "- **Un interrupteur ou un gradateur** : un gradateur est légèrement tiède en usage normal, mais s'il est chaud ou s'il sent, il est surchargé ou défectueux.",
    "- **Le panneau électrique** : une odeur près du panneau, avec ou sans bourdonnement, indique une connexion qui chauffe sur un disjoncteur ou sur la barre principale. C'est la situation la plus urgente, car toute l'alimentation de la maison passe par là.",
    "- **Un luminaire** : une ampoule de puissance trop élevée dans un plafonnier fermé, ou un ballast de fluorescent en fin de vie, dégagent une odeur de plastique chaud caractéristique.",
    "- **Un appareil** : chargeur, barre d'alimentation, réfrigérateur, sécheuse. Débranchez-le et voyez si l'odeur cesse. Si elle persiste, le problème est dans la prise ou le mur, pas dans l'appareil.",
    "Si vous ne trouvez pas la source mais que l'odeur est nette et persistante, considérez que c'est le mur ou le panneau, et passez au protocole ci-dessous.",
    "## Le protocole des 5 premières minutes",
    "### Minute 0 à 1 : couper",
    "Coupez le disjoncteur du circuit concerné. Si vous ne savez pas lequel, ou si l'odeur vient du panneau lui-même, coupez le disjoncteur principal, à condition de pouvoir le faire avec les mains sèches et sans toucher une partie chaude, décolorée ou qui grésille. Si le panneau est chaud, fume ou crépite, ne vous en approchez pas : sortez et composez le 911.",
    "### Minute 1 à 2 : éloigner",
    "Écartez tout ce qui est inflammable de la zone : rideaux, papier, coussins, meubles collés à la prise. Débranchez les appareils du circuit, en tirant sur la fiche et non sur le cordon, sans toucher une fiche chaude. Faites sortir les enfants et les animaux de la pièce.",
    "### Minute 2 à 3 : ne pas ouvrir",
    "N'ouvrez ni le panneau ni la prise pour « voir ». N'enlevez pas la plaque. N'aspergez jamais d'eau une prise ou un panneau, même après avoir coupé le courant. Ne réenclenchez pas le disjoncteur pour vérifier si l'odeur revient. L'intérieur d'un panneau reste sous tension même quand le principal est coupé.",
    "### Minute 3 à 4 : évaluer",
    "Y a-t-il de la fumée, même légère, ou une lueur derrière la prise ? Une plaque qui noircit ? Un bruit de crépitement qui continue ? Dans l'un ou l'autre de ces cas, sortez de la maison et composez le 911. Un feu électrique dans un mur peut couver plusieurs minutes avant d'apparaître.",
    "### Minute 4 à 5 : appeler",
    "S'il n'y a ni fumée ni flamme, appelez un électricien d'urgence au [(438) 338-4113](tel:+14383384113). Décrivez l'odeur, sa localisation, ce que vous avez coupé et les appareils qui fonctionnaient. Ces détails accélèrent le diagnostic. Ne remettez pas le courant en attendant, même si l'odeur a disparu : la connexion qui a chauffé est toujours là.",
    "## Les causes fréquentes d'une odeur de brûlé électrique",
    "### La connexion desserrée",
    "C'est la cause numéro un. Une vis de borne qui s'est desserrée avec les années, un fil simplement enfoncé dans un connecteur rapide à l'arrière d'une prise, un marret mal serré : le contact devient partiel, la résistance augmente, et le point de contact chauffe chaque fois que le circuit est sollicité. Cette chaleur cuit lentement le plastique autour. C'est un défaut invisible de l'extérieur et impossible à diagnostiquer sans ouvrir la boîte.",
    "### L'arc électrique",
    "Quand une connexion desserrée s'ouvre et se referme sous tension, elle produit une petite étincelle, un arc. L'arc atteint des milliers de degrés sur une surface minuscule. C'est lui qui laisse des traces noires autour d'une prise et qui dégage l'odeur d'ozone. C'est aussi le principal mécanisme des incendies d'origine électrique. Un [disjoncteur AFCI](/services/remplacement-disjoncteur) est conçu pour le détecter, mais beaucoup de logements montréalais n'en sont pas équipés.",
    "### La surcharge",
    "Un chauffage d'appoint de 1 500 watts branché sur une barre d'alimentation, elle-même branchée sur une rallonge : la prise, la fiche et le cordon chauffent tous, et l'odeur de plastique apparaît. Le circuit peut tenir sans que le disjoncteur saute, mais chaque composant travaille à sa limite. Si votre disjoncteur saute aussi à répétition, notre article sur le [disjoncteur qui saute sans arrêt](/blog/disjoncteur-saute-sans-arret-causes-urgence) complète celui-ci.",
    "### Le câblage en aluminium",
    "De nombreuses maisons et immeubles construits entre le milieu des années 1960 et la fin des années 1970 au Québec ont été câblés en aluminium. L'aluminium se dilate et se contracte davantage que le cuivre, ce qui desserre les connexions avec le temps, et il s'oxyde, ce qui augmente la résistance. Résultat : des prises et interrupteurs qui chauffent, sans que rien ne paraisse. Si votre maison date de cette époque et qu'une odeur de brûlé apparaît, mentionnez-le à l'électricien.",
    "## Ce que fait l'électricien à son arrivée",
    "Le rôle de l'électricien n'est pas de remettre le courant et de partir. Il commence par sécuriser : vérifier que le bon circuit est coupé, repérer toute chaleur résiduelle et s'assurer qu'aucun feu ne couve. Il localise ensuite la source avec précision, souvent à l'aide d'une caméra thermique qui révèle un point chaud derrière une plaque ou dans le panneau, sans rien démonter à l'aveugle.",
    "Il ouvre alors la prise, la boîte ou le panneau concerné, mesure les connexions, remplace le dispositif brûlé et reprend la connexion défectueuse. Il vérifie ensuite le reste du circuit, parce qu'une connexion qui a chauffé a souvent endommagé le fil sur quelques centimètres, et parfois les boîtes voisines. Un [diagnostic électrique](/services/diagnostique-electrique) complet est proposé si l'installation présente d'autres faiblesses.",
    "Le diagnostic sur place est gratuit. Le prix de la réparation vous est annoncé avant de commencer, et il est identique de jour, de nuit, la fin de semaine ou un jour férié. Nos électriciens sont licenciés CMEQ / RBQ et interviennent à Montréal, Laval, Longueuil, Brossard, Terrebonne et sur les deux rives.",
    "## Prévenir la prochaine odeur de brûlé",
    "- Ne branchez jamais un chauffage d'appoint, un climatiseur ou une plaque de cuisson sur une rallonge ou une barre d'alimentation. Ces appareils vont directement dans une prise murale, seuls sur leur circuit si possible.",
    "- Remplacez toute prise dans laquelle les fiches tiennent mal : le contact lâche est une connexion desserrée en devenir.",
    "- Respectez la puissance maximale indiquée dans vos luminaires fermés.",
    "- Si votre maison a un câblage en aluminium ou un panneau de plus de 30 ans, faites faire une inspection préventive plutôt que d'attendre la première odeur.",
    "- Faites installer des disjoncteurs anti-arc sur les circuits des chambres et du salon lors de votre prochaine intervention au panneau.",
    "## Conclusion : l'odeur est l'avertissement, pas le problème",
    "Une odeur de brûlé électrique disparaît parfois d'elle-même quand le circuit refroidit. C'est le piège : la connexion qui a chauffé recommencera au prochain usage, un peu plus abîmée chaque fois, jusqu'au jour où l'avertissement sera de la fumée. Couper, éloigner, ne pas ouvrir, évaluer, appeler : ces cinq minutes sont la meilleure assurance contre un incendie.",
    "Vous sentez cette odeur en ce moment ? Coupez le circuit si c'est possible en sécurité et appelez-nous immédiatement au [(438) 338-4113](tel:+14383384113). Nous répondons 24/7 et arrivons en moins d'une heure dans le Grand Montréal. Pour une inspection préventive, [demandez une intervention](/contact).",
  ],
  faq: [
    {
      question: "Une odeur de brûlé électrique sans fumée, est-ce grave ?",
      answer:
        "Oui. L'odeur apparaît avant la fumée : elle signale qu'un isolant ou un boîtier commence à fondre sous l'effet d'une connexion qui chauffe. Le fait qu'il n'y ait pas encore de fumée ne veut pas dire que le problème est mineur, seulement qu'il en est à un stade précoce. Coupez le circuit concerné si vous pouvez le faire en sécurité et appelez un électricien d'urgence sans attendre.",
    },
    {
      question: "Pourquoi ma prise sent le poisson ?",
      answer:
        "Les plastiques et résines des prises, interrupteurs et disjoncteurs dégagent une odeur de poisson ou d'urine quand ils surchauffent. C'est un signe classique de surchauffe électrique, souvent confondu avec une odeur de cuisine. Si l'odeur est localisée près d'une prise, d'un interrupteur ou du panneau, coupez le disjoncteur correspondant, n'ouvrez rien et faites venir un électricien.",
    },
    {
      question: "Dois-je appeler le 911 ou un électricien pour une odeur de brûlé ?",
      answer:
        "Composez le 911 dès que vous voyez de la fumée, des flammes, une lueur derrière une prise, ou si le panneau est chaud et crépite. S'il n'y a qu'une odeur, sans fumée ni flamme, coupez le circuit concerné en sécurité, éloignez les matériaux inflammables et appelez un électricien d'urgence. Dans le doute, le 911 d'abord : les pompiers vérifient qu'aucun feu ne couve dans le mur.",
    },
    {
      question: "Puis-je remettre le courant si l'odeur de brûlé a disparu ?",
      answer:
        "Non. L'odeur disparaît quand la connexion refroidit, mais le défaut qui l'a causée, vis desserrée, arc, fil abîmé, est toujours là et recommencera à chauffer dès la remise sous tension, un peu plus endommagé chaque fois. Laissez le disjoncteur coupé jusqu'à ce qu'un électricien ait ouvert la boîte, identifié la source et réparé la connexion.",
    },
    {
      question: "Combien de temps faut-il à un électricien d'urgence pour arriver à Montréal ?",
      answer:
        "Notre équipe répond en moins d'une heure dans le Grand Montréal, incluant Laval, Longueuil, Brossard, Terrebonne et les deux rives, 24/7, 365 jours par année. Le diagnostic sur place est gratuit, le prix est annoncé avant la réparation et aucune surcharge ne s'applique la nuit, la fin de semaine ou les jours fériés. En attendant, gardez le circuit coupé et n'ouvrez rien.",
    },
  ],
};
