import type { BlogPost } from "@/lib/blog-types";

export const post: BlogPost = {
  slug: "panne-electrique-hiver-chauffage-gel-urgence",
  title: "Panne électrique en hiver au Québec : chauffage, gel et urgence",
  category: "Panne électrique",
  excerpt:
    "Panne électrique en hiver au Québec : plinthes éteintes, tuyaux qui gèlent vite. Quoi faire, quand c'est une urgence et comment préparer sa maison.",
  date: "2026-07-16",
  keywords: [
    "panne électrique hiver Québec",
    "panne de chauffage électrique urgence",
    "électricien d'urgence hiver Montréal",
    "tuyaux gelés panne électrique",
    "plinthes électriques ne chauffent plus",
    "câble d'entrée électrique glace",
    "génératrice commutateur de transfert",
    "inspection électrique avant l'hiver",
    "panne électrique grand froid",
    "électricien 24h Laval Rive-Nord",
  ],
  relatedServiceSlug: "depannage-urgence",
  content: [
    "Il est deux heures du matin, il fait moins vingt-cinq dehors et la maison est anormalement silencieuse. Les plinthes ne cliquent plus, le ventilateur de la fournaise s'est tu et l'air commence déjà à fraîchir dans le couloir. Vous regardez par la fenêtre : les lampadaires sont allumés, la maison d'en face aussi. Ce n'est donc pas Hydro-Québec. Le problème est chez vous, et le compte à rebours vient de commencer.",
    "Au Québec, une panne électrique en hiver n'est pas une panne comme les autres. En été, on attend le matin avec une lampe de poche. En janvier, chaque heure sans chauffage rapproche vos tuyaux du gel, refroidit la chambre du bébé et met en danger les personnes fragiles de la maison. Ce guide explique pourquoi le froid change tout, quelles sont les causes typiques d'une panne hivernale, quoi faire dans les premières minutes et comment préparer votre maison pour ne pas revivre cette nuit-là.",
    "## Pourquoi une panne électrique en hiver est plus dangereuse",
    "### Le chauffage s'arrête d'un coup",
    "La grande majorité des maisons du Grand Montréal se chauffent à l'électricité : plinthes, convecteurs, thermopompe ou fournaise électrique. Même une fournaise au gaz ou au mazout dépend du courant pour son ventilateur et ses contrôles. Sans électricité, il n'y a plus de chaleur, point. Par grand froid, une maison bien isolée perd plusieurs degrés en quelques heures ; une maison ancienne ou mal isolée, beaucoup plus vite.",
    "### Les tuyaux peuvent geler en quelques heures",
    "C'est le dommage le plus coûteux d'une panne d'hiver. Les tuyaux qui longent un mur extérieur, ceux d'un vide sanitaire, d'un garage attenant ou d'une salle de bain au-dessus d'une entrée non chauffée gèlent en premier. L'eau qui gèle prend de l'expansion, fend le tuyau, et au dégel c'est l'inondation dans les murs et les plafonds.",
    "### Les personnes vulnérables n'ont pas de marge",
    "Un nourrisson, une personne âgée, quelqu'un qui relève d'une maladie ou qui dépend d'un appareil médical électrique (concentrateur d'oxygène, appareil pour l'apnée du sommeil, lit médicalisé) ne peut pas simplement « s'habiller plus chaud et attendre ». Dans ces situations, la panne devient une urgence dès la première heure, et il faut le dire clairement quand vous appelez.",
    "## Les causes hivernales les plus fréquentes",
    "L'hiver ne provoque pas de nouvelles pannes par magie : il pousse simplement votre installation électrique à sa limite, et les faiblesses existantes lâchent. Voici ce que nos électriciens rencontrent le plus souvent entre décembre et mars.",
    "- **Surcharge liée au chauffage.** Les plinthes tournent au maximum, une ou deux chaufferettes d'appoint s'ajoutent sur des circuits déjà chargés, et un disjoncteur finit par sauter. Si c'est le disjoncteur principal qui déclenche ou qui ne tient plus, le panneau lui-même est peut-être à bout de capacité. Notre article sur [le disjoncteur qui saute sans arrêt](/blog/disjoncteur-saute-sans-arret-causes-urgence) détaille les causes à écarter.",
    "- **Câble d'entrée abîmé par la glace et le vent.** Sur un branchement aérien, le poids du verglas et les rafales tirent sur le câble, tordent le mât d'entrée ou arrachent l'ancrage sur la maison. Le résultat est une connexion qui chauffe, un neutre qui se dégrade ou une panne partielle où la moitié de la maison fonctionne encore.",
    "- **Humidité et condensation dans le panneau.** Un panneau installé dans un sous-sol frais ou près d'un mur extérieur peut se couvrir de condensation quand l'air chaud de la maison rencontre le métal froid. Ajoutez une infiltration d'eau par le mât d'entrée et vous obtenez de la corrosion sur les cosses principales, exactement là où passe tout le courant de la maison.",
    "- **Composants fatigués qui lâchent à la pointe.** Un vieux disjoncteur, un panneau à fusibles ou un thermostat de plinthe défectueux tiennent l'été sans problème et rendent l'âme la première nuit à moins trente, quand la charge est à son maximum.",
    "## Quoi faire immédiatement quand ça arrive",
    "Les gestes des quinze premières minutes déterminent si la nuit se termine par une réparation ou par un sinistre. Gardez la tête froide et suivez cet ordre.",
    "- Regardez dehors : si les voisins et les lampadaires sont éteints, c'est une panne de réseau. Signalez-la à Hydro-Québec et passez directement aux mesures de protection ci-dessous.",
    "- Si les voisins ont du courant, allez au panneau avec une lampe de poche et les mains sèches. Un disjoncteur déclenché peut être réenclenché une seule fois. S'il ressaute, s'il est chaud ou si vous sentez une odeur de brûlé, n'insistez pas.",
    "- N'ouvrez jamais le couvercle du panneau. Vous pouvez actionner les manettes, rien de plus. L'intérieur reste sous tension même quand le disjoncteur principal est coupé.",
    "- Coupez les thermostats des plinthes et éteignez les gros appareils. Au retour du courant, tout redémarrera en même temps et vous éviterez un nouveau déclenchement.",
    "- Ouvrez les portes des armoires sous les éviers pour que l'air de la pièce atteigne la tuyauterie, et laissez couler un mince filet d'eau froide au robinet le plus éloigné de l'entrée d'eau.",
    "- Regroupez la famille dans une seule pièce, fermez les portes, bouchez le bas des portes avec des serviettes. Habillez les enfants en couches et couvrez les fenêtres.",
    "- N'utilisez jamais de barbecue, de chaufferette au propane, de génératrice ou de cuisinière au gaz à l'intérieur pour vous chauffer. Le monoxyde de carbone tue plus vite que le froid.",
    "- Si vous voyez de la fumée ou des flammes, sortez et composez le 911 avant toute autre chose.",
    "Pour tenir le coup en attendant l'intervention, notre guide sur [la panne électrique de nuit](/blog/panne-electrique-nuit-quoi-faire-en-attendant-electricien) donne d'autres conseils pratiques, éclairage et sécurité compris.",
    "## Quand c'est une urgence même si Hydro-Québec n'est pas en cause",
    "Voici les situations où il faut appeler tout de suite plutôt que d'attendre le matin.",
    "- Les voisins ont du courant et pas vous, ou seulement une partie de la maison fonctionne. Le problème est dans votre installation ou votre branchement, et Hydro-Québec ne le réparera pas. Notre article [Hydro-Québec ou électricien : qui appeler ?](/blog/hydro-quebec-ou-electricien-qui-appeler-panne) clarifie qui fait quoi.",
    "- Le disjoncteur principal a sauté et ne tient plus, ou vous entendez un grésillement ou un bourdonnement au panneau.",
    "- Le câble d'entrée pend, le mât est plié ou l'ancrage a été arraché par le vent. Ne vous en approchez pas et ne touchez à rien de métallique autour.",
    "- Une odeur de plastique chaud ou de brûlé se dégage du panneau, d'une plinthe ou d'une prise.",
    "- Il fait moins quinze ou plus froid dehors, la température intérieure baisse vite, ou une personne vulnérable habite la maison.",
    "Dans tous ces cas, notre service de [dépannage électrique d'urgence 24/7](/services/depannage-urgence) répond en moins d'une heure à Montréal, Laval, Longueuil, Brossard, Terrebonne et sur les deux rives, 365 jours par année. Le diagnostic sur place est gratuit, le prix est annoncé avant de commencer et il n'y a aucune surcharge pour la nuit, la fin de semaine ou un jour férié.",
    "## Préparer sa maison pour ne plus revivre ça",
    "### Génératrice : oui, mais avec un transfert sécuritaire",
    "Une génératrice peut sauver votre hiver, à condition d'être branchée correctement. Ne la reliez jamais à une prise de la maison avec un câble « mâle-mâle ». Cette pratique renvoie du courant dans le réseau, peut électrocuter un monteur d'Hydro-Québec qui travaille sur la ligne et détruit vos appareils au retour du courant. La seule méthode sécuritaire et conforme est un commutateur de transfert installé par un électricien licencié, qui isole votre maison du réseau et alimente les circuits essentiels : fournaise ou quelques plinthes, réfrigérateur, pompe de puisard, un circuit d'éclairage. La génératrice elle-même doit rester dehors, loin des fenêtres et des entrées d'air.",
    "### Une inspection électrique avant l'hiver",
    "La meilleure panne est celle qui n'arrive pas. Un [diagnostic électrique](/services/diagnostique-electrique) à l'automne permet de resserrer les connexions au panneau, de repérer par thermographie les disjoncteurs et les cosses qui chauffent, de vérifier l'état du câble d'entrée et du mât, et de confirmer que la capacité du panneau suffit à la charge de chauffage. Si le panneau est un vieux modèle à fusibles ou un panneau reconnu pour ses défaillances, une [mise à niveau du panneau électrique](/services/panneau-electrique) avant décembre est un investissement bien plus rentable qu'un remplacement forcé en pleine tempête.",
    "### Les gestes simples qui évitent la surcharge",
    "- Une seule chaufferette d'appoint par circuit, branchée directement au mur, jamais sur une rallonge ni sur une barre d'alimentation.",
    "- Faites vérifier les thermostats de plinthes qui claquent, chauffent ou ne coupent plus.",
    "- Dégagez la neige et la glace autour du compteur, du mât d'entrée et de la thermopompe après chaque tempête.",
    "- Repérez le disjoncteur principal et l'entrée d'eau à l'avance, et gardez une lampe de poche à côté du panneau.",
    "## Conclusion : par grand froid, n'attendez pas le matin",
    "Une panne électrique en hiver au Québec est une course contre le froid. Les plinthes qui s'éteignent, les tuyaux qui gèlent et les personnes fragiles de la maison ne laissent pas la marge d'attendre huit heures pour « voir demain ». Vérifiez les voisins, réenclenchez une fois, coupez le chauffage pour éviter la surcharge au retour du courant, protégez la tuyauterie, et si le problème est chez vous, appelez sans hésiter. N'ouvrez jamais le panneau, ne chauffez jamais avec un appareil à combustion à l'intérieur, et composez le 911 s'il y a de la fumée ou des flammes.",
    "Vous êtes sans chauffage en ce moment ? Appelez-nous au (438) 338-4113 : un électricien licencié est en route en moins d'une heure, de jour comme de nuit. Pour préparer votre maison avant les grands froids, vous pouvez aussi [demander une inspection](/contact) et nous planifierons une visite à votre convenance.",
  ],
  faq: [
    {
      question: "Combien de temps mes tuyaux peuvent-ils tenir sans chauffage en hiver ?",
      answer:
        "Cela dépend de l'isolation et de la température extérieure, mais par moins vingt, les tuyaux d'un mur extérieur ou d'un vide sanitaire peuvent geler en quelques heures seulement. Ouvrez les armoires sous les éviers, laissez couler un filet d'eau et appelez un électricien d'urgence dès que la panne semble venir de votre installation. Une intervention de nuit coûte bien moins qu'un tuyau éclaté.",
    },
    {
      question: "Comment savoir si la panne vient d'Hydro-Québec ou de ma maison ?",
      answer:
        "Regardez les voisins et les lampadaires. S'ils sont éteints aussi, c'est une panne de réseau à signaler à Hydro-Québec. Si les voisins ont du courant, ou si seule une partie de votre maison fonctionne, le problème est dans votre panneau ou votre branchement d'entrée. Dans ce cas, seul un électricien licencié peut intervenir, et nous répondons en moins d'une heure, 24/7.",
    },
    {
      question: "Puis-je brancher ma génératrice dans une prise de la maison ?",
      answer:
        "Non, jamais. Un câble branché dans une prise renvoie du courant dans le réseau, peut électrocuter les monteurs d'Hydro-Québec et endommager vos appareils au retour du courant. La seule méthode sécuritaire est un commutateur de transfert installé par un électricien licencié, qui isole votre maison et alimente les circuits essentiels. La génératrice doit toujours rester à l'extérieur, loin des fenêtres.",
    },
    {
      question: "Un électricien se déplace-t-il vraiment la nuit par grand froid ?",
      answer:
        "Oui. Notre équipe est disponible 24/7, 365 jours par année, à Montréal, Laval, Longueuil, Brossard, Terrebonne et sur les deux rives, avec une réponse en moins d'une heure. Le diagnostic sur place est gratuit, le prix est annoncé avant de commencer et il n'y a aucune surcharge pour la nuit, la fin de semaine ou un jour férié, tempête ou pas.",
    },
    {
      question: "Que faire si mon disjoncteur principal a sauté et ne tient plus ?",
      answer:
        "Réenclenchez-le une seule fois, mains sèches, sans ouvrir le couvercle du panneau. S'il ressaute, s'il est chaud au toucher ou si vous sentez une odeur de brûlé, laissez-le en position fermée et appelez un électricien d'urgence. Un disjoncteur principal qui ne tient plus signale une surcharge du panneau, une connexion qui chauffe ou un défaut sur l'entrée, et ces trois causes peuvent provoquer un incendie.",
    },
  ],
};
