import type { BlogPost } from "@/lib/blog-types";

export const post: BlogPost = {
  slug: "panne-electrique-commerce-restaurant-urgence-montreal",
  title: "Panne électrique en commerce ou restaurant : urgence 24/7 Montréal",
  category: "Urgence électrique",
  excerpt:
    "Panne électrique dans votre restaurant ou commerce à Montréal ? Électricien d'urgence commercial 24/7 : protocole du gérant, causes fréquentes et prévention.",
  date: "2026-06-25",
  keywords: [
    "électricien urgence commercial Montréal",
    "panne électrique restaurant",
    "électricien commercial 24/7 Montréal",
    "panne électrique commerce que faire",
    "dépannage électrique commercial urgent",
    "panneau triphasé restaurant panne",
    "électricien de nuit commerce Montréal",
    "entretien électrique préventif restaurant",
    "thermographie panneau commercial",
    "électricien commercial Laval Longueuil",
  ],
  relatedServiceSlug: "depannage-urgence",
  content: [
    "Vendredi, 18 h 45. La salle est pleine, la cuisine roule à plein régime, et d'un coup la moitié des lumières s'éteignent, la hotte s'arrête, les terminaux de paiement affichent un écran noir. Vous avez environ trente secondes pour décider quoi faire. Ce que vous ferez dans les minutes qui suivent déterminera si vous perdez une heure ou toute la soirée, et si votre inventaire réfrigéré survit à la nuit.",
    "Une panne électrique dans un commerce ou un restaurant n'est pas seulement un désagrément : c'est une hémorragie financière qui commence à la seconde où le courant tombe. Ce guide s'adresse aux propriétaires et aux gérants de Montréal, Laval, Longueuil et de la couronne : ce que coûte réellement chaque heure d'arrêt, les causes de panne les plus fréquentes dans un local commercial, le protocole à suivre pour la sécurité et la reprise rapide, et comment un électricien d'urgence commercial vous évite de fermer le lendemain.",
    "## Ce que coûte vraiment une heure sans électricité",
    "Les gérants sous-estiment presque toujours l'addition d'une panne, parce qu'ils ne comptent que les ventes perdues pendant la coupure. La facture réelle est bien plus large.",
    "- **Les frigos et congélateurs.** Une chambre froide fermée tient quelques heures, un réfrigérateur de comptoir beaucoup moins. Passé un certain délai, les normes de salubrité imposent de jeter les aliments périssables. Pour un restaurant, c'est souvent plusieurs milliers de dollars d'inventaire.",
    "- **La cuisson et la ventilation.** Sans hotte, on ne peut pas cuisiner, même au gaz. Sans four ni plaques électriques, le service s'arrête net.",
    "- **Les caisses et les terminaux.** Pas de paiement, pas de vente. Les clients déjà attablés partent parfois sans pouvoir régler, et les réservations suivantes sont annulées.",
    "- **La sécurité.** Éclairage d'urgence, système d'alarme, caméras, réfrigération des médicaments en pharmacie, portes automatiques : tout ce qui protège vos clients et vos biens dépend du courant.",
    "- **Le personnel et la réputation.** Une équipe payée à ne rien faire, puis une soirée gâchée qui se retrouve dans les avis en ligne dès le lendemain.",
    "## Les causes de panne les plus fréquentes en commerce",
    "Un local commercial demande beaucoup plus à son installation électrique qu'une maison. Les équipements tournent des heures d'affilée, la charge est élevée et les pannes ont des origines particulières.",
    "### La surcharge en cuisine",
    "Un restaurant accumule les gros consommateurs : fours, friteuses, plaques, lave-vaisselle, chauffe-plats, machines à glace. Au fil des ans, on ajoute un appareil ici, une prise là, souvent sur des circuits déjà chargés. Les disjoncteurs sautent au coup de feu, précisément quand tout tourne en même temps.",
    "### Le panneau triphasé et ses particularités",
    "La plupart des commerces sont alimentés en triphasé. La perte d'une seule phase, par un fusible fondu, une connexion lâche ou un problème sur le branchement, provoque une panne partielle déroutante : une partie de l'éclairage fonctionne, certains moteurs peinent ou bourdonnent, d'autres équipements sont morts. Faire fonctionner un moteur triphasé sur deux phases le détruit en quelques minutes. C'est un cas où il faut couper les équipements et appeler rapidement.",
    "### L'éclairage et les ballasts",
    "Les luminaires commerciaux, surtout les anciens ballasts fluorescents ou les transformateurs d'enseignes, vieillissent mal. Un ballast qui chauffe ou qui court-circuite peut faire sauter tout un circuit d'éclairage de salle en pleine soirée, et dégager une odeur de brûlé qui inquiète les clients.",
    "### Les compresseurs et la réfrigération",
    "Les compresseurs de chambres froides, de vitrines et de climatisation tirent un fort courant au démarrage. Un condensateur fatigué, un contacteur usé ou un circuit sous-dimensionné font déclencher le disjoncteur ou, pire, laissent le compresseur chauffer jusqu'à la panne.",
    "### Le vieillissement de l'installation",
    "Beaucoup de commerces montréalais occupent des bâtiments anciens avec des panneaux datant de plusieurs décennies, des connexions corrodées, des boîtes surchargées et des ajouts successifs par différents entrepreneurs. Les signes d'un panneau en fin de vie sont décrits dans notre article sur [les vieux panneaux à fusibles et les modèles à risque](/blog/vieux-panneau-fusibles-federal-pioneer-risque-urgence).",
    "## Le protocole du gérant pendant une panne",
    "Un gérant qui a un plan garde le contrôle de la salle et raccourcit la panne. Voici la séquence à afficher dans le bureau et à faire connaître au personnel.",
    "- **Sécurité des clients d'abord.** Vérifiez que l'éclairage d'urgence s'est allumé et que les sorties sont visibles. Rassurez la salle calmement. S'il y a de la fumée, des flammes ou une odeur de brûlé forte, évacuez par les sorties d'urgence et composez le 911 avant tout.",
    "- **Fermez la cuisine.** Coupez les appareils à gaz, les friteuses et tout ce qui chauffe, pour éviter les brûlures et les redémarrages non contrôlés.",
    "- **Coupez les équipements sensibles.** Éteignez les compresseurs, les caisses, les ordinateurs et les moteurs. Au retour du courant, tout ne doit pas repartir en même temps, et les équipements triphasés ne doivent pas tourner sur une phase manquante.",
    "- **Gardez les frigos fermés.** Chaque ouverture fait perdre des degrés. Notez l'heure de la panne pour justifier plus tard la conservation ou la destruction des aliments.",
    "- **Vérifiez le voisinage.** Si les commerces voisins et la rue sont éteints, c'est une panne de réseau à signaler à Hydro-Québec. Si vous êtes le seul dans le noir, ou si seule une partie du local est touchée, le problème est dans votre installation et Hydro-Québec ne pourra rien faire.",
    "- **Ne touchez pas au panneau au-delà des manettes.** Réenclenchez un disjoncteur une seule fois, mains sèches, sans ouvrir le couvercle. S'il ressaute, s'il est chaud ou s'il grésille, laissez-le coupé.",
    "- **Appelez un électricien d'urgence commercial** en décrivant précisément ce qui s'est passé : quels équipements sont morts, lesquels fonctionnent, odeurs, bruits, moment exact. Ces détails accélèrent le diagnostic.",
    "Pour les décisions à prendre dans les premières minutes, notre article sur [quand appeler un électricien d'urgence à Montréal](/blog/electricien-urgence-montreal-24h-quand-appeler) complète cette liste.",
    "## Intervenir la nuit pour ne pas fermer le jour",
    "Notre équipe de [dépannage électrique d'urgence](/services/depannage-urgence) est disponible 24/7, 365 jours par année, et répond en moins d'une heure à Montréal, Laval, Longueuil, Brossard, Terrebonne et sur les deux rives. Sur place, l'électricien sécurise l'installation, pose un diagnostic gratuit, vous explique ce qui doit être réparé maintenant et ce qui peut attendre, puis vous annonce le prix avant de toucher à quoi que ce soit.",
    "Quand la réparation complète demande du temps, par exemple le remplacement d'un panneau ou la reprise d'un circuit de cuisine, nous privilégions une remise en service sécuritaire le soir même et planifions les travaux lourds pendant vos heures de fermeture, la nuit ou tôt le matin. L'objectif est simple : vous ouvrez à l'heure prévue le lendemain. Il n'y a chez nous aucune surcharge pour la nuit, la fin de semaine ou les jours fériés. Notre article sur [le coût d'un électricien d'urgence la nuit et la fin de semaine](/blog/cout-electricien-urgence-montreal-nuit-fin-de-semaine) explique ce qui influence réellement la facture.",
    "## Prévenir la prochaine panne",
    "Chaque intervention d'urgence dans un commerce révèle presque toujours un problème qu'un entretien aurait détecté. Quelques mesures réduisent nettement le risque d'une coupure en plein service.",
    "- **Un entretien électrique annuel.** Resserrage des connexions au panneau, vérification des contacteurs et des condensateurs de compresseurs, test des disjoncteurs, contrôle de l'éclairage d'urgence. Une visite en heures creuses, une fois par année, évite bien des soirées perdues.",
    "- **Une thermographie du panneau et des équipements.** Une caméra infrarouge repère les disjoncteurs, les cosses et les moteurs qui chauffent anormalement, des semaines avant qu'ils ne lâchent. C'est l'outil le plus efficace pour prévoir une panne plutôt que la subir.",
    "- **Des circuits dédiés pour les équipements critiques.** Réfrigération, hotte, caisses et réseau informatique méritent chacun leur circuit, pour qu'une friteuse en surcharge ne coupe pas la chambre froide.",
    "- **Un panneau adapté à la charge réelle.** Si vous avez ajouté des équipements depuis l'ouverture, faites évaluer la capacité de votre panneau. Une [mise à niveau du panneau électrique](/services/panneau-electrique) ou l'ajout d'un sous-panneau de cuisine élimine les surcharges chroniques.",
    "- **Un plan de panne écrit**, avec l'emplacement du panneau, la liste des équipements à couper, le numéro de l'électricien d'urgence et celui d'Hydro-Québec.",
    "Ces travaux relèvent de nos [services d'électricité commerciale](/services/travaux-electricite) et se planifient toujours en dehors de vos heures d'ouverture.",
    "## Conformité : ce qu'un commerce ne peut pas ignorer",
    "Un établissement qui reçoit du public a des obligations précises. Les travaux électriques doivent être exécutés par un entrepreneur électricien licencié (CMEQ / RBQ), et une réparation faite par un employé bien intentionné peut invalider votre assurance en cas d'incendie ou de blessure. L'éclairage d'urgence et les indications de sortie doivent fonctionner et être vérifiés régulièrement. Les modifications au panneau ou à l'entrée électrique doivent être déclarées et conformes au Code. Enfin, un rapport d'intervention d'électricien licencié après une panne sert de preuve auprès de l'assureur pour les pertes d'inventaire et les dommages aux équipements.",
    "## Conclusion : une panne en service se gère, elle ne s'improvise pas",
    "Dans un restaurant ou un commerce, chaque minute sans courant coûte de l'inventaire, des ventes et de la réputation. Les causes sont souvent prévisibles : surcharge de cuisine, phase perdue sur un panneau triphasé, ballast en fin de vie, compresseur fatigué, installation vieillissante. Le protocole aussi : sécurité des clients, cuisine fermée, équipements coupés, frigos fermés, vérification du voisinage, un seul réenclenchement, puis l'appel. N'ouvrez jamais le panneau, ne laissez jamais un employé improviser une réparation, et composez le 911 en présence de flammes ou de fumée.",
    "Votre commerce est en panne en ce moment ? Appelez-nous au (438) 338-4113 : un électricien licencié arrive en moins d'une heure, de jour comme de nuit, sans surcharge. Pour un entretien préventif ou une thermographie en heures creuses, [demandez une soumission](/contact) et nous planifierons la visite selon vos heures d'ouverture.",
  ],
  faq: [
    {
      question: "En combien de temps un électricien d'urgence commercial peut-il arriver à Montréal ?",
      answer:
        "Notre équipe répond en moins d'une heure, 24/7 et 365 jours par année, à Montréal, Laval, Longueuil, Brossard, Terrebonne et sur les deux rives. En attendant, assurez la sécurité des clients, coupez les appareils de cuisson et les équipements sensibles, gardez les frigos fermés et notez précisément ce qui fonctionne encore. Ces informations accélèrent le diagnostic à l'arrivée de l'électricien.",
    },
    {
      question: "Seule une partie de mon restaurant est sans courant : est-ce Hydro-Québec ?",
      answer:
        "Probablement pas. Une panne partielle, surtout sur une alimentation triphasée, signale souvent une phase perdue, une connexion lâche ou un problème au panneau, donc dans votre installation. Coupez immédiatement les compresseurs et les moteurs, qui se détruisent en tournant sur une phase manquante, et appelez un électricien d'urgence. Si tout le quartier est éteint, c'est alors une panne de réseau à signaler à Hydro-Québec.",
    },
    {
      question: "Combien de temps mes frigos et ma chambre froide peuvent-ils tenir ?",
      answer:
        "Une chambre froide bien fermée conserve sa température quelques heures ; un réfrigérateur de comptoir ou une vitrine beaucoup moins. Gardez les portes fermées, notez l'heure de la panne et surveillez la température à intervalles réguliers. Une intervention en moins d'une heure limite souvent les pertes à zéro, alors qu'attendre le lendemain matin signifie presque toujours jeter les périssables.",
    },
    {
      question: "Un électricien peut-il intervenir la nuit pour éviter de fermer le lendemain ?",
      answer:
        "Oui, c'est précisément notre façon de travailler avec les commerces. Nous sécurisons et remettons en service le soir même quand c'est possible, puis planifions les travaux plus longs pendant vos heures de fermeture. Le diagnostic est gratuit, le prix est annoncé avant les travaux et il n'y a aucune surcharge pour la nuit, la fin de semaine ou les jours fériés.",
    },
    {
      question: "Mon employé peut-il réenclencher le disjoncteur ou réparer lui-même ?",
      answer:
        "Il peut réenclencher un disjoncteur une seule fois, mains sèches, sans ouvrir le couvercle du panneau. S'il ressaute, s'il est chaud ou s'il grésille, il faut le laisser coupé. Toute réparation doit être faite par un électricien licencié (CMEQ / RBQ) : une intervention improvisée peut blesser, aggraver la panne et annuler votre couverture d'assurance. En cas de fumée ou de flammes, évacuez et composez le 911.",
    },
  ],
};
