import type { BlogPost } from "@/lib/blog-types";

export const post: BlogPost = {
  slug: "panne-electrique-nuit-quoi-faire-en-attendant-electricien",
  title: "Panne électrique la nuit : quoi faire en attendant l'électricien",
  category: "Panne électrique",
  excerpt:
    "Panne électrique la nuit à Montréal ? Gestes de sécurité, erreurs à éviter et quoi préparer avant l'arrivée de l'électricien de nuit, en moins d'une heure.",
  date: "2026-09-03",
  keywords: [
    "panne électrique nuit Montréal",
    "électricien de nuit Montréal",
    "quoi faire panne électrique",
    "panne de courant la nuit",
    "électricien d'urgence 24h",
    "disjoncteur principal qui saute",
    "panne électrique hiver chauffage",
    "en attendant l'électricien",
    "urgence électrique nuit Laval Longueuil",
    "dépannage électrique de nuit",
  ],
  relatedServiceSlug: "depannage-urgence",
  content: [
    "Il est 1 h 30. Le bruit du frigo s'est tu, la veilleuse du couloir s'est éteinte et la maison est plongée dans un silence inhabituel. Vous tâtonnez jusqu'à la fenêtre : chez le voisin, une lumière brille encore. Ce n'est donc pas le quartier, c'est chez vous. Une panne électrique la nuit à Montréal a quelque chose de déstabilisant : on ne voit rien, on ne sait pas d'où vient le problème et, l'hiver, on sent déjà la température baisser.",
    "La bonne nouvelle, c'est qu'un électricien de nuit peut être chez vous en moins d'une heure. La moins bonne, c'est que les gestes posés pendant cette heure d'attente font souvent la différence entre une réparation simple et un problème aggravé. Voici, dans l'ordre, ce qu'il faut faire, ce qu'il faut vérifier, ce qu'il ne faut surtout pas faire, et comment préparer l'arrivée de l'électricien.",
    "## Les premières minutes : la sécurité d'abord",
    "Avant de chercher la cause, assurez-vous que personne n'est en danger. Trois questions rapides.",
    "- Y a-t-il une odeur de brûlé, de la fumée ou des flammes quelque part ? Si oui, sortez avec tous les occupants et composez le 911 avant tout autre appel.",
    "- Entendez-vous un grésillement, un bourdonnement ou un claquement provenant du panneau ou d'un mur ? C'est le signe d'un arc électrique actif : n'approchez pas, ne touchez à rien.",
    "- Quelqu'un a-t-il reçu une décharge en touchant un appareil, un robinet ou une poignée ? Éloignez tout le monde de la zone concernée.",
    "Si aucune de ces situations ne s'applique, vous avez le temps de faire les vérifications qui suivent, calmement, avec une lampe de poche. Si l'une d'elles s'applique, appelez immédiatement notre [service de dépannage d'urgence](/services/depannage-urgence) au (438) 338-4113 après avoir mis les occupants en sécurité.",
    "## Étape 1 : vérifier si la panne vient du réseau ou de chez vous",
    "Une panne complète peut venir d'Hydro-Québec ou de votre installation. Deux indices permettent de trancher rapidement.",
    "- Regardez chez les voisins et dans la rue : si les lampadaires et les maisons voisines sont éteints, il s'agit probablement d'une panne de réseau.",
    "- Consultez Info-pannes d'Hydro-Québec sur votre téléphone : si votre secteur est déjà signalé, la panne est de leur côté et un électricien ne peut rien y faire.",
    "Si les voisins ont du courant et que votre adresse n'apparaît pas sur Info-pannes, le problème est vraisemblablement chez vous : mât, entrée électrique, panneau ou câblage. Pour comprendre la répartition des responsabilités, consultez notre article [Hydro-Québec ou électricien : qui appeler en cas de panne](/blog/hydro-quebec-ou-electricien-qui-appeler-panne).",
    "## Étape 2 : jeter un coup d'œil au disjoncteur principal, sans ouvrir le panneau",
    "Rendez-vous au panneau avec votre lampe de poche. Ne l'ouvrez pas : regardez uniquement la face avant, celle où se trouvent les manettes des disjoncteurs.",
    "- Le disjoncteur principal, souvent en haut, est-il en position centrale ou « off » ? Un déclenchement du principal signale une surcharge générale ou un défaut important.",
    "- Un disjoncteur secondaire a-t-il sauté ? Il sera légèrement décalé par rapport aux autres.",
    "- Sentez-vous de la chaleur en approchant la main de la face avant du panneau, ou une odeur particulière ? Si oui, reculez et n'y touchez plus.",
    "Si un seul disjoncteur secondaire a sauté et que le panneau est froid et silencieux, vous pouvez le réenclencher une fois, les mains sèches, en le poussant franchement vers « off » puis vers « on ». S'il ressaute immédiatement ou dans les minutes qui suivent, n'insistez pas : il vous dit qu'un problème persiste sur ce circuit. Si c'est le disjoncteur principal qui a déclenché, ou si vous avez le moindre doute, laissez-le tel quel et appelez. Un principal qui saute la nuit, sans cause évidente, mérite un [diagnostic électrique](/services/diagnostique-electrique) avant toute remise sous tension.",
    "## Étape 3 : débrancher les appareils sensibles",
    "Quand le courant reviendra, il peut revenir avec une pointe de tension, ou de façon instable si le problème vient de l'entrée électrique. Profitez de l'attente pour protéger ce qui coûte cher.",
    "- Ordinateurs, téléviseurs, consoles et équipements audio.",
    "- Électroménagers récents munis de cartes électroniques : laveuse, sécheuse, lave-vaisselle, four.",
    "- Chargeurs de téléphone et borne de recharge de véhicule électrique.",
    "- Pompe de puisard et appareils médicaux, que vous rebrancherez en premier une fois le courant stable.",
    "Laissez le réfrigérateur et le congélateur fermés : sans ouverture, un frigo garde le froid environ quatre heures et un congélateur plein jusqu'à quarante-huit heures.",
    "## Étape 4 : s'éclairer sans risque",
    "Le premier réflexe est souvent la chandelle. C'est le mauvais réflexe, surtout dans une maison où l'origine de la panne est inconnue. Utilisez plutôt la lampe de poche du téléphone, une lampe frontale ou une lanterne à piles. Gardez le téléphone chargé le plus possible : c'est votre lien avec l'électricien et, au besoin, avec les secours. Une batterie externe rangée dans le tiroir de la cuisine vaut son pesant d'or ces nuits-là.",
    "## Étape 5 : gérer le froid si c'est l'hiver",
    "À Montréal, une panne de nuit en janvier n'est pas seulement un inconvénient : en quelques heures, la température intérieure chute et les tuyaux peuvent geler. Quelques gestes limitent les dégâts pendant l'attente.",
    "- Regroupez tout le monde dans une seule pièce, de préférence au centre de la maison, porte fermée, avec couvertures et vêtements chauds.",
    "- Fermez les rideaux et bloquez le bas des portes pour ralentir la perte de chaleur.",
    "- Laissez couler un mince filet d'eau froide au robinet le plus éloigné de l'entrée d'eau si la panne s'annonce longue.",
    "- N'utilisez jamais de barbecue, de chauffe-terrasse ou de génératrice à l'intérieur, ni dans le garage : le risque d'intoxication au monoxyde de carbone est mortel.",
    "- Si vous avez un foyer au bois en bon état, utilisez-le avec les précautions habituelles.",
    "Notre article sur [la panne électrique en hiver et le risque de gel](/blog/panne-electrique-hiver-chauffage-gel-urgence) approfondit ce scénario, y compris pour les maisons chauffées aux plinthes électriques.",
    "## Ce qu'il ne faut PAS faire pendant une panne de nuit",
    "Dans le noir, fatigué et un peu inquiet, on prend de mauvaises décisions. Voici celles que nous voyons le plus souvent, et qui transforment une panne banale en intervention lourde.",
    "- Ouvrir le panneau électrique pour « regarder ». L'intérieur reste sous tension même quand le principal est coupé. C'est le geste le plus dangereux de la liste.",
    "- Réenclencher le même disjoncteur trois, quatre, cinq fois. Chaque déclenchement chauffe davantage la connexion défaillante.",
    "- Toucher un fil, une prise ou un appareil avec les mains mouillées, ou marcher dans une zone inondée où des appareils sont branchés.",
    "- Alimenter la maison avec une rallonge tirée de chez le voisin, ou brancher une génératrice dans une prise murale : c'est dangereux pour vous, pour les monteurs d'Hydro-Québec et pour votre installation.",
    "- Remplacer un fusible par un fusible de calibre plus élevé, ou par un morceau de métal, dans un vieux panneau.",
    "- Allumer des chandelles et s'endormir.",
    "- Attendre le matin quand ça sent le brûlé ou que ça grésille, « pour ne pas déranger ».",
    "## Quoi préparer pour l'arrivée de l'électricien",
    "Un électricien de nuit qui arrive chez vous en moins d'une heure gagne encore du temps si vous avez préparé le terrain. Cela accélère le diagnostic et réduit la durée de l'intervention.",
    "- Dégagez l'accès au panneau électrique : déplacez les boîtes, les vélos ou les étagères qui le bloquent.",
    "- Notez ce que vous avez observé : l'heure de la panne, ce qui fonctionnait à ce moment-là, les bruits, les odeurs ou les lumières qui ont vacillé avant.",
    "- Localisez l'entrée électrique extérieure et le compteur, et déneigez l'accès l'hiver.",
    "- Préparez la liste des appareils qui ont cessé de fonctionner et de ceux qui fonctionnent encore, si la panne est partielle.",
    "- Gardez une pièce d'identité et, si vous êtes locataire, le numéro du propriétaire à portée de main.",
    "- Tenez les animaux dans une pièce fermée pour la durée de l'intervention.",
    "À son arrivée, l'électricien sécurise l'installation, pose un diagnostic gratuit sur place, vous explique la cause et vous annonce le prix avant de commencer la réparation. Il n'y a aucune surcharge de nuit : le tarif est le même qu'en plein jour.",
    "## Conclusion : agissez calmement, puis appelez",
    "Une panne électrique la nuit se gère en cinq réflexes : sécuriser les occupants, vérifier si le réseau est en cause, regarder le disjoncteur principal sans ouvrir le panneau, débrancher ce qui est sensible et s'éclairer sans flamme. Le reste appartient à un électricien licencié, équipé pour travailler dans le noir et en sécurité.",
    "Vous êtes dans le noir en ce moment ? Composez le [(438) 338-4113](tel:+14383384113) : un électricien de nuit est chez vous en moins d'une heure, partout à Montréal, Laval, Longueuil, Brossard, Terrebonne et sur les deux rives. Pour une situation moins pressante, [demandez une intervention en ligne](/contact).",
  ],
  faq: [
    {
      question: "Est-ce que je peux appeler un électricien en pleine nuit à Montréal ?",
      answer:
        "Oui. Notre service de dépannage fonctionne 24/7, 365 jours par année, avec une réponse en moins d'une heure dans le Grand Montréal. Une personne vous répond, vous donne les consignes de sécurité et envoie l'électricien de garde le plus proche. Le diagnostic sur place est gratuit, le prix est annoncé avant la réparation et il n'y a aucune surcharge de nuit, de fin de semaine ou de jour férié.",
    },
    {
      question: "Comment savoir si la panne de nuit vient d'Hydro-Québec ou de chez moi ?",
      answer:
        "Regardez dehors : si les lampadaires et les maisons voisines sont éteints, c'est probablement le réseau. Consultez ensuite Info-pannes d'Hydro-Québec sur votre téléphone. Si votre secteur n'y figure pas et que les voisins ont du courant, le problème est chez vous (mât, entrée électrique, panneau ou câblage) et il faut un électricien. Une panne partielle ou des lumières qui varient pointent aussi vers votre installation.",
    },
    {
      question: "Puis-je réenclencher le disjoncteur qui a sauté ?",
      answer:
        "Une fois, si le panneau est froid, silencieux et sans odeur, les mains sèches, en poussant la manette franchement vers « off » puis vers « on ». S'il ressaute, n'insistez pas : chaque tentative chauffe davantage la connexion en cause. Si c'est le disjoncteur principal qui a déclenché, laissez-le coupé et appelez. N'ouvrez jamais le boîtier du panneau : l'intérieur reste sous tension même quand le principal est coupé.",
    },
    {
      question: "Que faire pour ne pas geler pendant une panne électrique en hiver ?",
      answer:
        "Regroupez les occupants dans une seule pièce, porte fermée, avec couvertures et vêtements chauds. Fermez les rideaux, bloquez le bas des portes et laissez couler un filet d'eau au robinet le plus éloigné pour éviter le gel des tuyaux. N'utilisez jamais de barbecue, de chauffe-terrasse ou de génératrice à l'intérieur ou dans le garage : le monoxyde de carbone tue. Appelez l'électricien sans attendre le matin.",
    },
    {
      question: "Qu'est-ce que je dois préparer avant l'arrivée de l'électricien de nuit ?",
      answer:
        "Dégagez l'accès au panneau électrique, notez l'heure de la panne et ce qui fonctionnait à ce moment, listez les appareils touchés si la panne est partielle, localisez l'entrée électrique et le compteur à l'extérieur, et déneigez l'accès l'hiver. Tenez les animaux dans une pièce fermée. Ces détails accélèrent le diagnostic gratuit et réduisent la durée de l'intervention, ce qui compte quand la maison refroidit.",
    },
  ],
};
